name: build

on:
  push

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Check cargo version
        run: |
          cargo version
      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cargo +nightly build --release -Zbuild-std=std,panic_abort -Z build-std-features=panic_immediate_abort
      - name: show build artifacts
        run: |
          du -sh target/*/release/main